### ISSUE TITLE
can't upgrade to redis 3.0

### ISSUE THREAD

**Issue by yoch** [sibson/redbeat#107]
Hi,

The new version of python redis (3.0) [is not backward compatible](https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30), and upgrading cause problems.

```
>>> entry.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/redbeat/schedulers.py", line 274, in save
    pipe.zadd(self.app.redbeat_conf.schedule_key, self.score, self.key)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/usr/local/lib/python3.5/dist-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'int' object has no attribute 'items'
```

**Comment by qzn928** [comment]
The same question......
`
[2019-03-04 19:51:51,332: WARNING/MainProcess] return iter(x.items())
[2019-03-04 19:51:51,332: WARNING/MainProcess] AttributeError
[2019-03-04 19:51:51,332: WARNING/MainProcess] :
[2019-03-04 19:51:51,332: WARNING/MainProcess] 'int' object has no attribute 'items'
`

**Comment by andonirodriguez** [comment]
Related. https://github.com/celery/celery/issues/5369

Any foresight to fix this? Thanks.

**Comment by sibson** [comment]
https://github.com/sibson/redbeat/pull/108

**Comment by victorct-pulsarup** [comment]
Any plans on releasing a new version with this bug fixed?

**Comment by laixintao** [comment]
New version support redis3 released. https://github.com/sibson/redbeat/issues/113
