### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by infa-vsinghal** [sibson/redbeat#169]
Hi,

I'm using redbeat v1.0.0 with Django==3.0.3, celery==4.4.0 in a multicontainer docker compose env. In my Django settings.py I've the following settings: 

```
# celery and redbeat
REDBEAT_REDIS_URL = "redis://redis:6379/1"
REDBEAT_KEY_PREFIX = "readbeat"
CELERY_BROKER_URL = 'redis://redis:6379'
CELERY_RESULT_BACKEND = 'redis://redis:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULE = {
     'say_hello_schedule': {
         'task': 'service_status.tasks.say_hello',
         'schedule': timedelta(hours=1),
     },}
```

and in celery.py
```
from __future__ import absolute_import
from django.conf import settings
from celery import Celery
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')

# redbeat
app = Celery('mysite')
app.conf.update(
    redbeat_redis_url="redis://redis:6379/1",
)
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
```

No error in starting up the environment. I then open Django shell with everything running fine in the background (other static scheduled tasks)
```
python3 manage.py shell
```

and run the following
```
from redbeat import RedBeatSchedulerEntry as Entry
from service_status import tasks
from celery import Celery
app = Celery('mysite')
e = Entry('hello_sch','tasks.hello_function',20,args=[],app=app)
e.save()
```

and get the following error
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/redbeat/schedulers.py", line 292, in save
    with get_redis(self.app).pipeline() as pipe:
  File "/usr/local/lib/python3.6/site-packages/redbeat/schedulers.py", line 114, in get_redis
    if conf.redis_url.startswith('redis-sentinel') and  'sentinels' in redis_options:
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I'm not using `sentinel` anywhere... How to fix this?

**Comment by infa-vsinghal** [comment]
I figured out the issue!

`app` was the issue all along. 
```
# app should be
from <path to celery.py> import app
e = Entry(name='hello_sch',task='service_status.tasks.hello_function',schedule=20,args=[],app=app)
e.save()
```

output
```
<RedBeatSchedulerEntry: hello_sch tasks.hello_function() <freq: 20.00 seconds>
```
