### ISSUE TITLE
No module named 'celery.five' on celery==5.0.0

### ISSUE THREAD

**Issue by 549982170** [sibson/redbeat#188]
Traceback (most recent call last):
  File "/home/backend/.pyenv/versions/3.8.2/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/bin/celery.py", line 150, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/bin/beat.py", line 70, in beat
    return beat().run()
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run
    self.start_scheduler()
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/apps/beat.py", line 96, in start_scheduler
    print(self.banner(service))
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/apps/beat.py", line 118, in banner
    c.reset(self.startup_info(service))),
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/apps/beat.py", line 128, in startup_info
    scheduler = service.get_scheduler(lazy=True)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/celery/beat.py", line 653, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/redbeat/__init__.py", line 3, in <module>
    from .schedulers import RedBeatScheduler, RedBeatSchedulerEntry  # noqa
  File "/home/backend/.pyenv/versions/3.8.2/lib/python3.8/site-packages/redbeat/schedulers.py", line 30, in <module>
    from celery.five import values
ModuleNotFoundError: No module named 'celery.five'

version：
celery-redbeat==1.0.0
celery==5.0.0

run command：
celery -A gin2 beat -S redbeat.RedBeatScheduler

**Comment by ronid** [comment]
It's already fixed in the master (checked locally) , can you please publish a new release? 
Thanks 🙏

**Comment by yogevyuval** [comment]
@sibson Seems like there is a lot of positive activity in the repo lately! Some of it contains fixes for some critical breakings like this, do you have plans to release a new version to PyPI or should we start using Redbeat from specific commits from Github?

**Comment by sibson** [comment]
I'm not actively running master, so have been waiting for feedback from others. Without positive confirmations I'm giving it some time to bake before a release.

**Comment by yogevyuval** [comment]
@sibson Ok I see. We will start using some pinned commit from the master and I will let you know how it goes after some production time.

**Comment by waltermaldonado** [comment]
I can confirm the bug, just pinned `celery==4.4.6` to get it working again. A release with the fix would be really useful.

**Comment by calumball** [comment]
@sibson When do you plan to cut a release? Thanks for your work on redbeat!
