### ISSUE TITLE
Redis connection errors during lock acquision causes duplicate schedulers to run at once

### ISSUE THREAD

**Issue by nigel-gott** [sibson/redbeat#208]
## The Problem

If any exception is raised whilst a redbeat scheduler is attempting to acquire a lock. The exception is swallowed by celery and redbeat starts running that scheduler and sending tasks as if it had acquired the lock, even though it has not. This results in scheduled tasks being sent multiple times if you have multiple redbeats running, one with and lock and the others which have raised an exception and started scheduling as a result.

## Our Setup 

We have a k8s cluster with two redbeats running at the same time. Usually, one redbeat acquires the redis lock and does all the scheduling. The other sleeps as a backup until it can acquire the lock and take over if the first crashes. Today we observed our scheduled tasks were running twice. Upon inspection both redbeats were running and sending tasks. The second redbeat which normally waits as backup had raised a `redis.exceptions.ConnectionError: Connection closed by server.` whilst attempting to acquire the lock. It then had immediately started to schedule tasks as if it held the lock (even though it did not).

## Logs

The "primary" redbeat which initially acquired the lock was working as normal, extending the lock etc.
```
[2021-08-09 09:23:47,402: DEBUG/MainProcess] beat: Synchronizing schedule...
[2021-08-09 09:23:47,402: DEBUG/MainProcess] beat: Extending lock...
[2021-08-09 09:23:47,403: DEBUG/MainProcess] Selecting tasks
[2021-08-09 09:23:47,404: DEBUG/MainProcess] Loading 1 tasks
[2021-08-09 09:23:47,405: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
[2021-08-09 09:28:47,434: DEBUG/MainProcess] beat: Synchronizing schedule...
[2021-08-09 09:28:47,442: DEBUG/MainProcess] beat: Extending lock...
[2021-08-09 09:28:47,444: DEBUG/MainProcess] Selecting tasks
[2021-08-09 09:28:47,445: DEBUG/MainProcess] Loading 3 tasks
```
However as you can see in the log below for the secondary redbeat the connection error followed by sending of tasks, with no mention of acquiring or extending of the lock.
```
[2021-07-21 15:40:34,205: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
[2021-07-21 15:40:34,205: DEBUG/MainProcess] beat: Acquiring lock...
[2021-08-09 06:22:28,315: ERROR/MainProcess] Signal handler <function acquire_distributed_beat_lock at 0x7fe7c5158170> raised: ConnectionErr
or('Connection closed by server.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.7/site-packages/redbeat/schedulers.py", line 520, in acquire_distributed_beat_lock
    lock.acquire()
  File "/usr/local/lib/python3.7/site-packages/redis/lock.py", line 187, in acquire
    if self.do_acquire(token):
  File "/usr/local/lib/python3.7/site-packages/redis/lock.py", line 203, in do_acquire
    if self.redis.set(self.name, token, nx=True, px=timeout):
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2021-08-09 06:22:28,329: DEBUG/MainProcess] Selecting tasks
...
[2021-08-09 06:22:28,887: DEBUG/MainProcess] Loading 1 tasks
[2021-08-09 06:22:28,912: DEBUG/MainProcess] beat: Waking up in 1.26 minutes.
[2021-08-09 06:23:44,493: DEBUG/MainProcess] beat: Synchronizing schedule...
[2021-08-09 06:23:44,493: DEBUG/MainProcess] Selecting tasks
[2021-08-09 06:23:44,495: DEBUG/MainProcess] Loading 3 tasks
[2021-08-09 06:23:44,497: INFO/MainProcess] Scheduler: Sending due task ...
```

## The Cause

1. By default  [RedBeatScheduler.lock](https://github.com/sibson/redbeat/blob/82110c5dbb6bd23533ddf46df1ceec1adb53f132/redbeat/schedulers.py#L356) = None 
1. Celery sends the `beat_init` signal
    1.  The redbeat specific `acquire_distributed_beat_lock` celery signal receiver is signaled and starts running
    1.  The distributed beat lock is attempted to be acquired, this could technically run forever until it gets the lock as some other redbeat process might have it already: [lock.acquire](https://github.com/sibson/redbeat/blob/82110c5dbb6bd23533ddf46df1ceec1adb53f132/redbeat/schedulers.py#L514) 
    1. At some point whilst [lock.acquire](https://github.com/sibson/redbeat/blob/82110c5dbb6bd23533ddf46df1ceec1adb53f132/redbeat/schedulers.py#L514) is running, the connection dies and a `redis.exceptions.ConnectionError: Connection closed by server.` is raised (or any other Exception) 
    1. This exception bubbles up back to Celery's signal handling code (this is not a normal django Signal, but instead Celeries own implementation!)
    1. Crucially, `scheduler.lock` is never set and remains None.
 1. Celeries own Signal handler swallows the exception and instead returns a list of tuples indicating an error has happened (https://github.com/celery/celery/blob/8ebcce1523d79039f23da748f00bec465951de2a/celery/utils/dispatch/signal.py#L254)
 1. [Celery Beat ignores any return value](https://github.com/celery/celery/blob/f462a437e3371acb867e94b52c2595b6d0a742d8/celery/beat.py#L638) from the `beat_init.send` and starts ticking the scheduler assuming everything is OK 
 1. `RedBeatScheduler.tick` assumes if `self.lock` is None then there is no lock being used, and that it should go ahead and schedule tasks. Whereas infact there is a lock being used, but instead it crashed whilst trying to be acquired.
 
## Possible Solutions

I'm happy to work on a fix for this however there are a number of different things that could be done. Is there a preferred solution / mix of solutions here? 

* Redbeat could catch and handle Connection errors when attempting to acquire the lock in a while loop until the lock is actually acquired
    1. Perhaps there is a parameter that could be passed to redis-py to have it do this by default?
* Redbeat could separate the concepts of "there is no lock being used" and "the lock has not been acquired", and then in the tick method if the state of "the lock has not been acquired" is encountered, then it could crash (or possibly try to acquire?)
* Celery Beat itself could inspect the return values from the `beat_init.send` and do something appropriate if the signal has failed. Most likely just re-raising and crashing.

**Comment by sibson** [comment]
Thanks for the writeup.  Without spiking out the options I don't have a real opinion on the "best" solution. I wouldn't bother trying to change the contract with Celery Beat, it feels like an uphill battle on the wrong hill.   It seems like there are multiple undesirable behaviours that should be addressed and thus a combination of the first two options would be best, though they could be implemented independently.  

In the signal handler, should redbeat crash if it fails to acquire the lock? Should it continually retry? I see arguments either way .  Retry is likely most similar to the current behaviour/expectations.

In tick(), I feel like trying to recover the lock is risky.  The original design assumed it was always running within the mutex, so I don't know what other possible bugs would creep in if you lost and regained the lock at various points, rather than rely on clean state from a startup.

**Comment by sibson** [comment]
Seems reasonable, two things I'd be cautious about.  First, catching all exception rather than only ConnectionErrors.  It could be the right thing to do, but I always feel nervous about catch all.  Second, can we throw earlier before tick(), maybe setup_schecule()? My reasoning being, earlier is better and we shouldn't need to pay the init failed tax every tick.

**Comment by nigel-gott** [comment]
After some time I finally got around to looking into this issue again and have raised an initial PR. I agree with being nervous about the catch alls, however I believe it is less of an issue in my PR as I immediately rethrow the exception and so can simply be seen as a non behaviour changing 'interceptor' of sorts. 

Also unfortunately we can't raise in setup_schedule as it has already been called by the time we are `acquire_distributed_beat_lock`. The first redbeat code that is called after `acquire_distributed_beat_lock` is the `tick` function and so that is where i've had to put the throw.

**Comment by sibson** [comment]
I believe this should now be fixed, please let me know how its working for you
