### ISSUE TITLE
Exception raised when calling task.revoke()

### ISSUE THREAD

**Issue by fxt** [sibson/redbeat#36]
We are getting exceptions in the celery-redbeat logs when using task.revoke():

[2016-08-11 15:10:55,512: INFO/MainProcess] beat: Starting...
[2016-08-11 15:10:55,537: CRITICAL/MainProcess] beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'now'",)
Traceback (most recent call last):
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 454, in start
    humanize_seconds(self.scheduler.max_interval))
  File ".../eggs/kombu-3.0.35-py2.7.egg/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 494, in scheduler
    return self.get_scheduler()
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 489, in get_scheduler
    lazy=lazy)
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File ".../eggs/celery_redbeat-0.9.2-py2.7.egg/redbeat/schedulers.py", line 187, in __init__
    super(RedBeatScheduler, self).__init__(app, **kwargs)
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File ".../eggs/celery_redbeat-0.9.2-py2.7.egg/redbeat/schedulers.py", line 196, in setup_schedule
    RedBeatSchedulerEntry(name).delete()
  File ".../eggs/celery_redbeat-0.9.2-py2.7.egg/redbeat/schedulers.py", line 65, in __init__
    args=args, kwargs=kwargs, **clsargs)
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 94, in __init__
    self.last_run_at = last_run_at or self._default_now()
  File ".../eggs/celery-3.1.18-py2.7.egg/celery/beat.py", line 98, in _default_now
    return self.schedule.now() if self.schedule else self.app.now()
AttributeError: 'NoneType' object has no attribute 'now'

Here is a patch that seemed to solve the problem:

--- redbeat/schedulers.py	2016-08-11 14:48:48.000000000 -0400
+++ redbeat/schedulers.py	2016-08-11 14:49:35.000000000 -0400
@@ -193,7 +193,7 @@
         current = set(self.app.conf.CELERYBEAT_SCHEDULE.keys())
         removed = previous - current
         for name in removed:
-            RedBeatSchedulerEntry(name).delete()
+            RedBeatSchedulerEntry(name, app=self.app).delete()
 
         # setup statics
         self.install_default_entries(self.app.conf.CELERYBEAT_SCHEDULE)

**Comment by sibson** [comment]
thanks for the report and proposed fix. I think the same fix is present in https://github.com/sibson/redbeat/pull/34, as such I'm closing this.  If its not fixed for you please re-open.
