### ISSUE TITLE
hi there is some wrong，it is cant no load the  “REDBEAT_REDIS_URL” correctly

### ISSUE THREAD

**Issue by sonlia** [sibson/redbeat#41]
celery beat v3.1.21 (Cipater) is starting.
__    -    ... __   -        _
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.default.Loader
    . scheduler -> redbeat.schedulers.RedBeatScheduler
       . redis -> None
       . lock -> `redbeat::lock` now (0s)
    . logfile -> [stderr]@%INFO
    . maxinterval -> now (0s)
[2016-11-28 13:50:38,391: INFO/MainProcess] beat: Starting...
[2016-11-28 13:50:38,392: CRITICAL/MainProcess] beat raised exception <type 'exceptions.AttributeError'>: AttributeError("'NoneType' object has no attribute 'find'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 112, in start_scheduler
    beat.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 470, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 325, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 512, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 507, in get_scheduler
    lazy=lazy)
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/redbeat/schedulers.py", line 190, in __init__
    super(RedBeatScheduler, self).__init__(app, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 185, in __init__
    self.setup_schedule()
  File "build/bdist.linux-x86_64/egg/redbeat/schedulers.py", line 194, in setup_schedule
    client = redis(self.app)
  File "build/bdist.linux-x86_64/egg/redbeat/schedulers.py", line 45, in redis
    decode_responses=True)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 391, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 774, in from_url
    url = urlparse(url)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
————————————————————————————————————————
and the config 
![uc 20161128215301](https://cloud.githubusercontent.com/assets/1559999/20670763/75ab9492-b5b5-11e6-851b-5fa5cf7c2fbf.png)

**Comment by sibson** [comment]
Hi,

My guess would be that your celery.py isn't importing the settings properly.

**Comment by nav005** [comment]
facing same issue. with celery 4.X
