### ISSUE TITLE
Getting Error NoneType has no attribute 'redbeat_conf'? 

### ISSUE THREAD

**Issue by chavenor** [sibson/redbeat#62]
I'm assuming it works on windows and there is something wrong with my script.
I'm also initialize the celery object from within the code.  See below. 

```python
#Add to config
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACKS_LATE = True
CELERY_PREFETCH_MULTIPLIER = 1
CELERY_CREATE_MISSING_QUEUES = True
REDBEAT_REDIS_URL = "x"
REDBEAT_KEY_PREFIX = "readbeat"
REDBEAT_LOCK_TIMEOUT = 100
CELERYBEAT_SCHEDULER = 'redbeat.RedBeatScheduler'
CELERYBEAT_MAX_LOOP_INTERVAL = 5  # redbeat likes fast loops



app = Celery('test_celery',
            broker='x',
            backend='x',
            include=['test_celery.tasks'],
            redis_max_connections = 3,
		result_persistent = True,
		enable_ut = True,
		timezone = "UTC",
		redis_socket_timeout = 15 ,
            event_serializer='json', 
            task_serializer='json',
            acks_late=True,
            prefetch_multiplier=1,
            create_missing_queues=True,
            schedule=RedBeatScheduler,

)

#Tried this. No error but nothing happens. 
app.conf.beat_schedule = {
    'add-every-30-seconds': {
        'task': 'tasks.email_check',
        'schedule': 30.0,
        'args': None
    },
}

#This threw error. 
interval = celery.schedules.schedule(run_every=30)  # seconds
entry = RedBeatSchedulerEntry('checkemails-task', 'tasks.email_check', interval,)
entry.save()


Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redbeat\schedulers.py", line 209, in save
    pipe.hset(self.key, 'definition', json.dumps(definition, cls=RedBeatJSONEncoder))
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redbeat\schedulers.py", line 188, in key
    return self.app.redbeat_conf.key_prefix + self.name
AttributeError: 'NoneType' object has no attribute 'redbeat_conf'
```

Launching the following without errors.

```bash 
celery -A test_celery beat -S redbeat.RedBeatScheduler
celery -A test_celery worker -E -l INFO -n workerA --loglevel=DEBUG --concurrency=1 -Ofair -c 3 -Q high,default
celery -A test_celery worker -E -l INFO -n workerB --loglevel=DEBUG --concurrency=1 -Ofair -c 3 -Q low
celery -A test_celery flower --port=2525 --persistent=true
```

**Comment by bentzirp** [comment]
solved?

**Comment by chavenor** [comment]
I did the above now getting the blow error message.  

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redbeat\schedulers.py", line 208, in save
    with redis(self.app).pipeline() as pipe:
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redbeat\schedulers.py", line 59, in redis
    decode_responses=True)
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redis\client.py", line 391, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "C:\Users\Casey\Envs\site-website\lib\site-packages\redis\connection.py", line 774, in from_url
    url = urlparse(url)
  File "C:\Python27\Lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\Lib\urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'

```

**Comment by sibson** [comment]
Is ```REDBEAT_REDIS_URL = "x"``` is a valid redis URL.
