### ISSUE TITLE
Redbeat doesn't work with Celery `4.2.0rc1`

### ISSUE THREAD

**Issue by fangpenlin** [sibson/redbeat#88]
Redbeat doesn't work with Celery `4.2.0rc1`

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/circleci/repo/tests/conftest.py", line 7, in <module>
    from myapp.app import create_app
  File "/home/circleci/repo/myapp/app.py", line 19, in <module>
    from myapp.settings import ProdConfig
  File "/home/circleci/repo/myapp/settings.py", line 7, in <module>
    from redbeat.decoder import RedBeatJSONDecoder
  File "/home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redbeat/__init__.py", line 3, in <module>
    from .schedulers import RedBeatScheduler, RedBeatSchedulerEntry  # noqa
  File "/home/circleci/.local/share/virtualenvs/repo-eQF46Ow3/lib/python3.6/site-packages/redbeat/schedulers.py", line 39, in <module>
    CELERY_4_OR_GREATER = StrictVersion(celery_version) >= StrictVersion('4.0')
  File "/usr/local/lib/python3.6/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.6/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '4.2.0rc1'
```

similar problem from other project

https://github.com/numpy/numpy/issues/7697

So I guess `distutils.version.StrictVersion` is not an ideal tool for determining the version of celery

**Comment by benjolitz** [comment]
Also does not work with ``3.1.26.post2``

**Comment by benjolitz** [comment]
I am currently using the following monkey patch until `StrictVersion` in schedulers is replaced with `pkg_resources.parse_version`, the expected supported manner (See https://github.com/pypa/setuptools/issues/1310#issuecomment-377078459)

This is due to StrictVersion throwing a ValueError, a rather unique exception to see on a package import. As is usual one must run the patches before any prior import.

```
def patch_redbeat():
    ''' Fix https://github.com/sibson/redbeat/issues/88
    '''
    try:
        from redbeat import schedulers
    except ValueError:
        from distutils import version
        cls = version.StrictVersion
        assert isinstance(cls, (type, old_style_class))
        version.StrictVersion = parse_version
        from redbeat import schedulers
        schedulers.StrictVersion = parse_version
        version.StrictVersion = cls
    else:
        if hasattr(schedulers, 'StrictVersion'):
            assert isinstance(schedulers.StrictVersion, type(parse_version))
```

**Comment by auvipy** [comment]
4.2.1 should work? may be redbeat cant parse string in version
